application: spayder26-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: 1.2

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/style/favicon.ico
  upload: static/style/favicon.ico

- url: /js
  static_dir: static/js

- url: /style/fixes
  static_dir: static/style/fixes

- url: /style
  static_dir: static/style

- url: /icons
  static_dir: static/icons

- url: /imgs
  static_dir: static/imgs

- url: /flags
  static_dir: static/flags

- url: /.*
  script: main.application

